AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetimetz
        nom:
            type: string
            length: '255'
        description:
            type: string
            length: '255'
        prix:
            type: float
        stockRestant:
            type: integer
    manyToMany:
        commandes:
            targetEntity: Commande
            inversedBy : articles
    lifecycleCallbacks: {  }
